Answer 3

In [1]:
import pandas as pd

In [2]:
df = pd.read_json('https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json')

In [3]:
df = pd.json_normalize(df['pokemon']) # normalizing the json data to readable columns

In [4]:
df.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [5]:
df_backup=df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              151 non-null    int64
 1   num             151 non-null    object
 2   name            151 non-null    object
 3   img             151 non-null    object
 4   type            151 non-null    object
 5   height          151 non-null    object
 6   weight          151 non-null    object
 7   candy           151 non-null    object
 8   candy_count     70 non-null     float64
 9   egg             151 non-null    object
 10  spawn_chance    151 non-null    float64
 11  avg_spawns      151 non-null    float64
 12  spawn_time      151 non-null    object
 13  multipliers     70 non-null     object
 14  weaknesses      151 non-null    object
 15  next_evolution  70 non-null     object
 16  prev_evolution  72 non-null     object
dtypes: float64(3), int64(1), object(13)
memory usage: 20.2+ KB

In [6]:
df['candy_count']=df['candy_count'].fillna(0).astype(int)

In [7]:
df['num']=df['num'].astype(int)
df_backup=df

In [8]:
df['height']=df['height'].str.extract('(\d+\.\d+)').astype(float)

In [9]:
df['weight']=df['weight'].str.extract('(\d+\.\d+)').astype(float)
df_backup=df

In [10]:
df['egg']=df['egg'].str.extract('(\d+)').fillna(0).astype(float)

In [11]:
df['avg_spawns']=df['avg_spawns'].astype(int)

In [12]:
df['spawn_time']=pd.to_timedelta(df['spawn_time']+':00', errors='coerce') #converter hh:mm to hh:mm:ss format and not time values to Nat

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              151 non-null    int64
 1   num             151 non-null    int64
 2   name            151 non-null    object
 3   img             151 non-null    object
 4   type            151 non-null    object
 5   height          151 non-null    float64
 6   weight          151 non-null    float64
 7   candy           151 non-null    object
 8   candy_count     151 non-null    int64
 9   egg             151 non-null    float64
 10  spawn_chance    151 non-null    float64
 11  avg_spawns      151 non-null    int64
 12  spawn_time      145 non-null    timedelta64[ns]
 13  multipliers     70 non-null     object
 14  weaknesses      151 non-null    object
 15  next_evolution  70 non-null     object
 16  prev_evolution  72 non-null     object
dtypes: float64(4), int64(4), object(8), timedelta64[ns](1)
memory usage: 20.2+ KB

In [14]:
df.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71,6.9,Bulbasaur Candy,25,2.0,0.690,69,0 days 20:00:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99,13.0,Bulbasaur Candy,100,0.0,0.042,4,0 days 07:00:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01,100.0,Bulbasaur Candy,0,0.0,0.017,1,0 days 11:30:00,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61,8.5,Charmander Candy,25,2.0,0.253,25,0 days 08:45:00,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09,19.0,Charmander Candy,100,0.0,0.012,1,0 days 19:00:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [15]:
df.to_excel('pokemon.xlsx')